all: one
	g++ -std=c++14 first.cpp -o first -lboost_system
	g++ -std=c++14 second.cpp -o second -lboost_system

one:
	g++ -std=c++14 spsc_cls_obj.cpp -o spsc_cls_obj -lboost_system
	g++ -std=c++14 spsc_cls_ptr.cpp -o spsc_cls_ptr -lboost_system

