all:
	g++ basic.cpp -o basic -lboost_system -lpthread -lboost_thread -lboost_chrono
	g++ spsc_class.cpp -o spsc_class -lboost_system -lpthread -lboost_thread -lboost_chrono

clean:
	rm -f basic spsc_class
