
all: array
	g++ -std=c++11 keyval.cpp -o keyval -lboost_system
	g++ -std=c++11 array.cpp -o array -lboost_system

array: 
	g++ -std=c++11 array.cpp -o array -lboost_system

clean:
	rm -f keyval array
