
all:
	g++ -std=c++11 -o receiver receiver.cpp -lboost_system -lpthread
	g++ -std=c++11 -o receiver2 receiver2.cpp -lboost_system -lpthread
	g++ -std=c++11 -o publisher publisher.cpp -lboost_system -lpthread

clean:
	rm -f receiver publisher

