#!/usr/bin/python

import sys, getopt
import subprocess
import os

def usage():
    print sys.argv[0], "-n <count>"

def main(argv):
    nQdump = 0
    try:
        opts, args = getopt.getopt(argv,"hn:",["n=",])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            usage()
            sys.exit()
        elif opt in ("-n", "--num_clients"):
            nQdump = int(arg)
        else:
            usage()
            sys.exit(2)
    print 'Number of client instances to launch: ', nQdump
    base_id = 1000
    filename = "/tmp/tcp_test.log"
    for x in range(1,nQdump+1):
        id_ = base_id + x
        print "Launcing...", id_
        cmd = "./TcpSocket --client >> " + filename + " 2>&1 &"
        print cmd
        os.system( cmd )

if __name__ == "__main__":
    if len(sys.argv) < 2:
        usage()
        sys.exit(2)
    main(sys.argv[1:])

